### ISSUE TITLE
Server fails to launch

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [null2264/SkyblockCreator#2]
```
[22:39:18] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'skyblockcreator'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.10.jar:?]
        at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.10-launcher.0.11.1.jar:0.11.1]
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: skyblockcreator:Start Island
        at net.minecraft.util.Identifier.<init>(Identifier:41) ~[?:?]
        at net.minecraft.util.Identifier.<init>(Identifier:50) ~[?:?]
        at io.github.null2264.skyblockcreator.core.ModServer.lambda$onInitializeServer$1(ModServer.java:53) ~[SkyblockCreator-1.3.2-ALPHA+1.18.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at io.github.null2264.skyblockcreator.core.ModServer.onInitializeServer(ModServer.java:52) ~[SkyblockCreator-1.3.2-ALPHA+1.18.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
        ... 8 more

```
Using 1.3.2 Alpha on 1.18.2. Fabric loader v0.14.10

**Comment by null2264** [comment]
You can't use spaces on your island ID, it's should only have `a to z` (**lowercase!**), `0 to 9`, `/`, `.`, `_`, and `-`. So in your case, it should either be named "start-island" or "start_island".

**Comment by FoxNerdSaysMoo** [comment]
Ok thanks, it worked in singleplayer which caused my confusion
